
module.exports=[
  {
    id:1,
    imgUrl:"../../images/item1.jpg",
    name:"美容养颜"
  },

  {
    id:2,
    imgUrl:"../../images/item2.jpg",
    name:"保健调养"
  },
  {
    id:3,
    imgUrl:"../../images/item3.jpg",
    name:"补养"
  },
  {
    id:4,
    imgUrl:"../../images/item4.jpg",
    name:"减肥"
  },
  {
    id:5,
    imgUrl:"../../images/item5.jpg",
    name:"母婴"
  },
  {
    id:6,
    imgUrl:"../../images/item6.jpg",
    name:"气节"
  },
  {
    id:7,
    imgUrl:"../../images/item7.jpg",
    name:"常见食疗"
  },

  {
    id:8,
    imgUrl:"../../images/item8.jpg",
    name:"维生素"
  }
]